# Generated by Django 4.2.3 on 2023-08-09 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Mazda', max_length=200, verbose_name='Marke')),
                ('model', models.CharField(default='MX-5', max_length=200, verbose_name='Modell')),
                ('serial_number', models.CharField(default='0', max_length=200, verbose_name='Fahrgestellnummer')),
                ('year', models.DateField(default=datetime.date.today, verbose_name='Erstzulassung')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Bob', max_length=200, verbose_name='Name')),
                ('street', models.CharField(default='Goslarer Str. 77', max_length=200, verbose_name='Straße')),
                ('area_code', models.IntegerField(default=38690, verbose_name='PLZ')),
                ('city', models.CharField(default='Goslar', max_length=200, verbose_name='Stadt')),
            ],
            options={
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Bob', max_length=200, verbose_name='Name')),
                ('street', models.CharField(default='Goslarer Str. 77', max_length=200, verbose_name='Straße')),
                ('area_code', models.IntegerField(default=38690, verbose_name='PLZ')),
                ('city', models.CharField(default='Goslar', max_length=200, verbose_name='Stadt')),
                ('make', models.CharField(default='Mazda', max_length=200, verbose_name='Marke')),
                ('model', models.CharField(default='MX-5', max_length=200, verbose_name='Modell')),
                ('serial_number', models.CharField(default='0', max_length=200, verbose_name='Fahrgestellnummer')),
                ('year', models.DateField(default=datetime.date.today, verbose_name='Erstzulassung')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Rechnungsdatum')),
                ('number', models.IntegerField(default=1, unique=True, verbose_name='Rechnungsnr.')),
                ('complete', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('tax', models.IntegerField(default=19, verbose_name='MWSt')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice')),
            ],
            options={
                'verbose_name_plural': 'Positionen',
            },
        ),
    ]
