# Generated by Django 4.2.3 on 2023-08-10 07:41

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='index',
            field=models.IntegerField(default=1, verbose_name='Pos.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(default=sales.models.get_new_invoice_number, unique=True, verbose_name='Rechnungsnummer'),
        ),
    ]
