# Generated by Django 4.2.3 on 2023-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_item_index_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index'], 'verbose_name_plural': 'Positionen'},
        ),
        migrations.AlterField(
            model_name='item',
            name='index',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Pos.'),
        ),
    ]
