# Generated by Django 4.2.3 on 2023-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_item_options_alter_item_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['index'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positionen'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='make',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='model',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='year',
        ),
        migrations.AlterField(
            model_name='client',
            name='area_code',
            field=models.PositiveIntegerField(default=0, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='area_code',
            field=models.PositiveIntegerField(default=0, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='Straße'),
        ),
    ]
