# Generated by Django 4.2.3 on 2023-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_item_options_remove_invoice_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Verkauft'),
        ),
    ]
