# Generated by Django 4.2.3 on 2023-09-13 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_car_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Betrag'),
        ),
    ]
