# Generated by Django 4.2.3 on 2023-09-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_car_colour_car_letter_no_car_odo_invoice_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='Anrede'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='Anrede'),
        ),
    ]
