# Generated by Django 4.2.3 on 2023-10-01 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_client_title_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.CharField(default='', max_length=20, verbose_name='Hubraum'),
        ),
        migrations.AddField(
            model_name='car',
            name='power_output',
            field=models.CharField(default='', max_length=20, verbose_name='PS/kW'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='capacity',
            field=models.CharField(default='', max_length=20, verbose_name='Hubraum'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.CharField(choices=[('c', 'Bar'), ('t', 'Überweisung')], default='c', max_length=2, verbose_name='Zahlungsmethode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='power_output',
            field=models.CharField(default='', max_length=20, verbose_name='PS/kW'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('25a', '§ 25a Differenzbesteuerung'), ('6a', '§ 6a Innergemeinschaftliche Lieferung'), ('4', '§ 4 Netto-Verkauf (Nicht-EU)'), ('4eu', '§ 4')], default='25a', max_length=5, verbose_name='Bedingungen'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Betrag (brutto)'),
        ),
    ]
