# Generated by Django 4.2.3 on 2023-10-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_car_capacity_car_power_output_invoice_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_tax_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ausweis- und/oder Steuernr.'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='id_tax_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ausweis- und/oder Steuernr.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Hubraum'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_output',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='PS/kW'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Hubraum'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='power_output',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='PS/kW'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('25a', '§ 25a Differenzbesteuerung'), ('6a', '§ 6a Innergemeinschaftliche Lieferung'), ('4', '§ 4 Netto-Verkauf (Nicht-EU)'), ('4eu', '§ 4 Netto-Verkauf (EU)')], default='25a', max_length=5, verbose_name='Bedingungen'),
        ),
    ]
