# Generated by Django 4.2.3 on 2023-10-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_client_id_tax_id_client_telephone_invoice_id_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tuev_au',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TÜV/AU'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tuev_au',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TÜV/AU'),
        ),
    ]
