# Generated by Django 4.2.3 on 2023-10-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_car_plate_invoice_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Fahrzeug', 'verbose_name_plural': '🚗 Fahrzeuge'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Kunde', 'verbose_name_plural': '👤 Kunden'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Rechnung', 'verbose_name_plural': '💰 Rechnungen'},
        ),
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='car',
            name='letter_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='KFZ-Brief-Nr.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Anrede'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='letter_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='KFZ-Brief-Nr.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='make',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Anrede'),
        ),
    ]
