# Generated by Django 4.2.3 on 2023-10-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_car_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Verkauf', 'verbose_name_plural': '💰 Verkäufe'},
        ),
    ]
