# Generated by Django 4.2.3 on 2023-10-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='25a', max_length=5, verbose_name='Bedingungen'),
        ),
    ]
