# Generated by Django 4.2.3 on 2023-10-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_invoice_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('25a', '§ 25a Differenzbesteuerung'), ('6a', '§ 6a Innergemeinschaftliche Lieferung'), ('4', '§ 4 Netto-Verkauf (Nicht-EU)'), ('4eu', '§ 4 Netto-Verkauf (EU)')], default='25a', max_length=5, verbose_name='Bedingungen'),
        ),
    ]
